# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk0y-q-FkUXvnAdrCMGMoGXybBfItl5k
"""

#KANAK CHOUKSEY
#TASK 1 TOP 3 MOST COMMON CUISINES

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns

df = pd.read_csv('/content/Dataset .csv')
df.head()

df.isnull().sum()

df['Cuisines'].unique()

Cuisines_no = df.Cuisines.value_counts()
Cuisines_no

columns_sorted = Cuisines_no.sort_values(ascending=False)
columns_sorted

Cuisine = df["Cuisines"]

Cuisine_count = Cuisine.value_counts()

Top_3_Cuisines = columns_sorted.head(3)

total = len(df)

percentage_of_Top_Cuisines = (Top_3_Cuisines/total)*100

print("TOP 3 Cuisines:")
Top_3_Cuisines

plt.bar(percentage_of_Top_Cuisines.index,percentage_of_Top_Cuisines.values, color = ['red'])
plt.xlabel("Cuisines")
plt.ylabel("percentage_of_Top_Cuisines")
plt.title("Top three most common Cuisines")
plt.show()

Restaurant  = df['Restaurant Name'].count()
Restaurant

total_restaurants = len(df)
Cuisine_percentage = Top_3_Cuisines / total_restaurants * 100

print("percentage_of_Top_3_Cuisines")
print(Cuisine_percentage)

